/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      gravity_compensation:
        type: crisp_controllers/CartesianImpedanceController

      cartesian_impedance_controller:
        type: crisp_controllers/CartesianImpedanceController

      pose_broadcaster:
        type: crisp_controllers/PoseBroadcaster

      hardware_components_initial_state:
        unconfigured:
          - "KortexMultiInterfaceHardware"

  joint_trajectory_controller:
    ros__parameters:
      command_interfaces:
        - effort
      state_interfaces:
        - position
        - velocity
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - joint_7
      gains:
        joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
        joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
        joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
        joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
        joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
        joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
        joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }

  joint_state_broadcaster:
    ros__parameters:
      use_local_topics: False

  pose_broadcaster:
    ros__parameters:
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - joint_7

      end_effector_frame: end_effector_link
      base_frame: base_link

  gravity_compensation:
    ros__parameters:
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - joint_7

      end_effector_frame: end_effector_link
      base_frame: base_link

      task:
        k_pos_x: 0.0
        k_pos_y: 0.0
        k_pos_z: 0.0
        k_rot_x: 30.0
        k_rot_y: 30.0
        k_rot_z: 30.0

      nullspace: 
        stiffness: 0.0

      use_friction: true
      use_coriolis_compensation: true
      use_local_jacobian: true

  cartesian_impedance_controller:
    ros__parameters:
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - joint_7

      end_effector_frame: end_effector_link
      base_frame: base_link

      filter:
        q: 0.5
        dq: 0.5
        output_torque: 0.5

      task:
        k_pos_x: 40.0
        k_pos_y: 40.0
        k_pos_z: 40.0
        k_rot_x: 3.0
        k_rot_y: 3.0
        k_rot_z: 3.0

      nullspace: 
        stiffness: 0.0
        projector_type: none
        weights: 
          - 1.0
          - 1.0
          - 1.0
          - 1.0
          - 1.0
          - 1.0
          - 1.0
      # log:
      #   enabled: true
      #   # robot_state: true
      #   timing: true

      use_friction: false
      use_coriolis_compensation: false
      use_local_jacobian: true

